language: python
    - "3.2"
    - "3.4"
    - "3.5"
    - "3.6"
cache: pip
install:
    - pip3 install codecov rednose nose-parameterized codeclimate-test-reporter
script: python3 setup.py test
sudo: false
dist: trusty